[tox]
envlist = py310, py311, py312, lint, typecheck
isolated_build = true

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --no-root
commands =
    poetry run pytest --cov=src --cov-report=term-missing

[testenv:lint]
commands =
    poetry run ruff check .
    poetry run ruff format --check .

[testenv:typecheck]
commands =
    poetry run mypy src
